name: PaperPing
main: com.xdefcon.spigotping.SpigotPing
author: xDefcon
version: '${version}'
api-version: "1.20"
description: "PaperPing a simple and customizable plugin to show your ping."
commands:
    ping:
      description: The main command for PaperPing.
    pingreload:
      description: Reloads the plugin.
